<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>WhiteMC</RootNamespace>
    <AssemblyName>WhiteMC</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <SatelliteResourceLanguages>en;ru</SatelliteResourceLanguages>

    <Product>WhiteMC</Product>
    <AssemblyTitle>WhiteMC</AssemblyTitle>
    <Company>aut1st1c</Company>
    <Copyright>Unlicensed</Copyright>

    <ApplicationIcon>Assets\whitemc.ico</ApplicationIcon>

    <Version>0.1.4</Version>
    <FileVersion>$(Version)</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.3" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.2.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Themes\**" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="installer.iss" />
  </ItemGroup>
</Project>