<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>WhiteMC</RootNamespace>
    <AssemblyName>WhiteMC</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PublishReadyToRun>false</PublishReadyToRun>
    <SatelliteResourceLanguages>en;ru</SatelliteResourceLanguages>
    <Version>0.1.0</Version>
    <FileVersion>$(Version)</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
  </PropertyGroup>
</Project>